services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ${PROJECT_NAME}_app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node",
          "-e",
          "fetch('http://localhost:${APP_PORT}/api/health').then(r => { if (!r.ok) process.exit(1) }).catch(() => process.exit(1))"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


    restart: unless-stopped
    networks:
      - road_book

  nginx:
    image: nginx:1.28-alpine
    container_name: ${PROJECT_NAME}_nginx
    environment:
      API_DOMAIN: ${API_DOMAIN}
      APP_PORT: ${APP_PORT}
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - road_book

  mysql:
    image: mysql:8.4
    container_name: ${PROJECT_NAME}_mysql
    command: --port=${MYSQL_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

    networks:
      - road_book

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

    command: >
      redis-server
      --port ${REDIS_PORT}
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    restart: unless-stopped

    networks:
      - road_book

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep PONG"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

volumes:
  mysql_data:
  redis_data:
  certbot_www:
  certbot_conf:

networks:
  road_book:
    driver: bridge